Sharing Language Keys Sample
gamerson/liferay-blade-samples pull request #215
Opened 2017-04-05 22:13 UTC by lawrence-lee

2017-04-05 22:15 UTC, lrbladejenkins commented
Test failed on LAX linux server on 254e994cd747757511a8c3b45ce31395497a3962

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/250/)

2017-04-05 22:17 UTC, lrbladejenkinswindows commented
Test failed on LAX windows server on 254e994cd747757511a8c3b45ce31395497a3962

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/169/)

2017-04-06 20:18 UTC, gamerson requested changes

2017-04-06 20:18 UTC, gamerson commented on liferay-workspace/modules/blade.language.web/src/main/resources/META-INF/resources/view.jsp
> +	<b><liferay-ui:message key="blade_language_web_LanguageWebPortlet.caption" /></b>
Lets show 3 captions here.

1) one caption load from blade.language module solely
2) one caption that is using a key that is defined in both language and langauge.web to show that language.web overrides it
3) one caption that only exists in language.web

2017-04-06 22:30 UTC, lrbladejenkins commented
Test failed on LAX linux server on bf825562f6ba4a22e936876689ee17340865fe8a

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/251/)

2017-04-06 22:31 UTC, lrbladejenkinswindows commented
Test failed on LAX windows server on bf825562f6ba4a22e936876689ee17340865fe8a

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/170/)

2017-04-06 22:49 UTC, lrbladejenkins commented
Test failed on LAX linux server on 99fed741d19b3299b7cace3475fc6e95c532cfe7

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/252/)

2017-04-06 22:50 UTC, lrbladejenkinswindows commented
Test failed on LAX windows server on 99fed741d19b3299b7cace3475fc6e95c532cfe7

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/171/)

2017-04-07 14:02 UTC, lrbladejenkins commented
Test failed on LAX linux server on 4e8a56af698a9c60d0b64dd141d629ca5518ebb7

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/253/)

2017-04-07 14:05 UTC, lrbladejenkinswindows commented
Test failed on LAX windows server on 4e8a56af698a9c60d0b64dd141d629ca5518ebb7

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/172/)

2017-04-07 14:14 UTC, lrbladejenkinswindows commented
Test Passed on LAX windows server on c089f5b82694e77f4b6a622db9aa9454bdd730e8

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/173/)

2017-04-07 14:18 UTC, lrbladejenkins commented
Test Passed on LAX linux server on c089f5b82694e77f4b6a622db9aa9454bdd730e8

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/254/)

2017-04-07 14:30 UTC, lawrence-lee commented
@gamerson tests passed!

2017-04-07 15:12 UTC, gamerson commented
@lawrence-lee Sweet!

2017-04-07 17:01 UTC, gamerson commented
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/216. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/c54f285~1...c54f285) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-04-07 17:01 UTC, closed without merging

2018-07-18 21:25 UTC, gamerson commented
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/493. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*