Add SB Integration Test
gamerson/liferay-blade-samples pull request #247
Opened 2017-05-24 17:51 UTC by lawrence-lee

2017-05-24 17:53 UTC, lrbladejenkins commented
Test failed on LAX linux server on 16d3726ac09685af6041235d9467e1ada2afe705

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/337/)

2017-05-24 20:50 UTC, lrbladejenkins commented
Test failed on LAX linux server on 5739eefcc2a5b57d500417a04b7d9ebf28c5317b

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/338/)

2017-05-24 21:56 UTC, lrbladejenkins commented
Test failed on LAX linux server on d3e708635445271c69058d7528ea923a32d18503

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/339/)

2017-05-25 13:22 UTC, lawrence-lee commented
jenkins retest

2017-05-25 13:24 UTC, lrbladejenkins commented
Test failed on LAX linux server on d3e708635445271c69058d7528ea923a32d18503

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/340/)

2017-05-25 15:00 UTC, lawrence-lee commented
jenkins retest

2017-05-25 15:16 UTC, lrbladejenkins commented
Test Passed on LAX linux server on d3e708635445271c69058d7528ea923a32d18503

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/341/)

2017-05-25 15:32 UTC, lrbladejenkins commented
Test Passed on LAX linux server on ec6b23405f117ba5f360edbe935d2a379ae19ad5

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/342/)

2017-05-25 15:35 UTC, gamerson requested changes

2017-05-25 15:35 UTC, gamerson commented on liferay-gradle/blade.servicebuilder.svc/src/testIntegration/java/com/liferay/blade/samples/servicebuilder/service/test/BladeServiceBuilderIntegrationTest.java
> +		JMXBundleDeployer jmxBundleDeployer = new JMXBundleDeployer(
Hey lets use this class from this dependency: `biz.aQute.bnd:biz.aQute.remote.api:3.3.0`

2017-05-25 15:35 UTC, gamerson commented on liferay-gradle/blade.servicebuilder.svc/build.gradle
> +	dependsOn ":blade.servicebuilder.api:deploy"
We don't need to both deploy this and then later install it with JMXDeployer.  Lets just use the JMX deployer for now and not the gradle deploy.

2017-05-25 15:35 UTC, gamerson commented on liferay-gradle/blade.servicebuilder.svc/source-formatter.properties
> +    src/testIntegration/java/com/liferay/blade/samples/servicebuilder/service/test/BladeServiceBuilderIntegrationTest.java,\
Lets go ahead and remove this and just fix the source formatter errors.

2017-05-25 15:35 UTC, gamerson commented on liferay-workspace/tests/arquillian.extension.lifecycle/src/main/java/org/jboss/arquillian/showcase/extension/lifecycle/LifecycleExecuter.java
> +/*
WHat are these classes?  Can we remove them?

2017-05-25 16:40 UTC, lrbladejenkins commented
Test failed on LAX linux server on bfab08f9035064b1dbdababb54d66652cbd82cd8

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/343/)

2017-05-25 21:25 UTC, closed without merging