add sample wars to BladeSamplesTest.testAllBladeSamples
gamerson/liferay-blade-samples pull request #310
Opened 2017-07-31 22:28 UTC by lawrence-lee

2017-07-31 22:31 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 260f5b77ad816d4aa3beaa2c321428be40141130

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/459/)

2017-07-31 22:36 UTC, lrbladejenkins commented
Test failed on LAX linux server on 260f5b77ad816d4aa3beaa2c321428be40141130 against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/21/)

2017-07-31 23:20 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 719b28c81049de8beee69fcba1cf68c7e78133f6

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/460/)

2017-07-31 23:25 UTC, lrbladejenkins commented
Test failed on LAX linux server on 719b28c81049de8beee69fcba1cf68c7e78133f6 against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/22/)

2017-08-01 02:28 UTC, lawrence-lee commented
I'm not sure why ```try (Jar jar = new Jar(sampleBundleFile, sampleBundleFile))``` throws a NPE. I can't reproduce this error locally. Can you give it a try tmrw?

2017-08-01 13:35 UTC, gamerson requested changes

2017-08-01 13:35 UTC, gamerson commented on liferay-workspace/tests/blade.samples.integration.test/src/testIntegration/java/com/liferay/blade/samples/test/BladeSamplesTest.java
> +				printFileName = new File(sampleBundleFile).getName();
Set the `new File(sampleBundleFile)` to a new variable `sampleBundleFile`

Then make sure that `sampleBundleFile` exists.  If it exists, then on 139 do this `Jar jar = new Jar(sampleBundleFile)`

2017-08-01 14:30 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 874cf4a6a81b0bcb6306353d48d19424a5a2c16e

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/462/)

2017-08-01 14:32 UTC, lrbladejenkins commented
Test failed on LAX linux server on 874cf4a6a81b0bcb6306353d48d19424a5a2c16e against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/24/)

2017-08-01 14:42 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 3e204da6a44f40d4536cb82ad92f146bc202d64b

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/464/)

2017-08-01 14:52 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 3e204da6a44f40d4536cb82ad92f146bc202d64b against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/26/)

2017-08-01 15:05 UTC, lrbladejenkins commented
Test failed on LAX linux server on 3e204da6a44f40d4536cb82ad92f146bc202d64b against latest 7010

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/11/)

2017-08-01 15:41 UTC, lawrence-lee commented
There's a bug on the latest bundle of 7010 where it won't start up. Thats why this is failing

2017-08-01 16:26 UTC, closed without merging