Kotlin Portlet - Removed Maven
gamerson/liferay-blade-samples pull request #389
Opened 2017-10-24 16:22 UTC by vishal-reddy

n Kotlin Portlet removed due to compiler JavaC compiler differences + Rebased

2017-10-24 16:28 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on 3e692d128e88572307cb45f4b8c2b9ac55547793

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/680/)

2017-10-24 16:31 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on 3e692d128e88572307cb45f4b8c2b9ac55547793

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/352/)

2017-10-24 16:34 UTC, gamerson commented
jenkins retest

2017-10-24 16:36 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on 3e692d128e88572307cb45f4b8c2b9ac55547793

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/353/)

2017-10-24 16:40 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on 3e692d128e88572307cb45f4b8c2b9ac55547793

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/681/)

2017-10-24 16:43 UTC, gamerson requested changes

2017-10-24 16:43 UTC, gamerson commented on gradle/settings.gradle
> +    'apps:kotlin-portlet',
Check whitespace here.

2017-10-24 16:43 UTC, gamerson commented on maven/apps/pom.xml
> +		<module>kotlin-portlet</module>
need to remove this here.

2017-10-24 16:44 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on eda5c701687004485b4533b10ed7f299c6982a6b

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/354/)

2017-10-24 16:48 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on 09dd99b10e7bcd6dfcd92b0b2ad59a0b17aea984

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/355/)

2017-10-24 16:48 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on eda5c701687004485b4533b10ed7f299c6982a6b

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/682/)

2017-10-24 16:53 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on 09dd99b10e7bcd6dfcd92b0b2ad59a0b17aea984

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/683/)

2017-10-24 17:07 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on d8f6d7ee28a47ff8f08403782503874be1ca32e9

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/356/)

2017-10-24 17:08 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on d8f6d7ee28a47ff8f08403782503874be1ca32e9

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/684/)

2017-10-24 17:09 UTC, vishal-reddy commented
jenkins retest

2017-10-24 17:10 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on d8f6d7ee28a47ff8f08403782503874be1ca32e9

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/357/)

2017-10-24 17:14 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on d8f6d7ee28a47ff8f08403782503874be1ca32e9

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/685/)

2017-10-25 23:53 UTC, vishal-reddy commented
jenkins retest

2017-10-25 23:54 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on d8f6d7ee28a47ff8f08403782503874be1ca32e9

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/358/)

2017-10-25 23:58 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on d8f6d7ee28a47ff8f08403782503874be1ca32e9

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/686/)

2017-10-26 20:09 UTC, gamerson commented
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/390. [See changes here.](https://github.com/gamerson/liferay-blade-samples/compare/bc52b7c~3...bc52b7c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-10-26 20:09 UTC, closed without merging