Add verification in samples
gamerson/liferay-blade-samples pull request #452
Opened 2018-03-15 18:31 UTC by lawrence-lee

2018-03-15 18:36 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on c8987efb31a114c382f6298f927dc3741014804e

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/851/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/851/consoleText)

2018-03-15 18:41 UTC, lrbladejenkinswindows commented
Bundle Diff Test failed on LAX windows server on c8987efb31a114c382f6298f927dc3741014804e

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/525/)

2018-03-16 16:01 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/854/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/854/consoleText)

2018-03-16 16:22 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd against latest GA

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/268/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/268/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-ga/268/consoleText)

2018-03-16 16:43 UTC, lrbladejenkinswindows commented
Bundles Diff Test Passed on LAX windows server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/528/)

2018-03-16 17:24 UTC, lrbladejenkins commented
Test failed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd against latest 7.1

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/5/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/5/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7.1/5/consoleText)

2018-03-16 18:35 UTC, lrbladejenkins commented
Test failed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd against latest 7010

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/129/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/129/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7010/129/consoleText)

2018-03-16 18:59 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/146/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/146/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-dxp/146/consoleText)

2018-03-16 20:12 UTC, lrbladejenkins commented
Test failed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd against latest master

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/133/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/133/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-master/133/consoleText)

2018-03-16 20:15 UTC, lawrence-lee commented
ci:retest

2018-03-16 20:17 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/855/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/855/consoleText)

2018-03-16 20:48 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 56e5169a643d35a746c2c388c1bc025393eede0f

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/856/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/856/consoleText)

2018-03-16 21:09 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 56e5169a643d35a746c2c388c1bc025393eede0f against latest GA

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/269/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/269/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-ga/269/consoleText)

2018-03-16 21:21 UTC, lrbladejenkinswindows commented
Bundles Diff Test Passed on LAX windows server on 29e20cc0163dcb34d36bce2d8d02b7ec0f4523bd

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/529/)

2018-03-16 21:33 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 56e5169a643d35a746c2c388c1bc025393eede0f against latest 7.1

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/6/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/6/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7.1/6/consoleText)

2018-03-16 21:44 UTC, lrbladejenkins commented
Test failed on LAX linux server on 56e5169a643d35a746c2c388c1bc025393eede0f against latest 7010

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/130/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/130/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7010/130/consoleText)

2018-03-16 22:08 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 56e5169a643d35a746c2c388c1bc025393eede0f against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/147/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/147/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-dxp/147/consoleText)

2018-03-16 22:21 UTC, lrbladejenkins commented
Test failed on LAX linux server on 56e5169a643d35a746c2c388c1bc025393eede0f against latest master

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/134/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/134/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-master/134/consoleText)

2018-03-16 22:27 UTC, lrbladejenkinswindows commented
Bundles Diff Test Passed on LAX windows server on 56e5169a643d35a746c2c388c1bc025393eede0f

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/530/)

2018-03-16 23:06 UTC, gamerson requested changes

2018-03-16 23:06 UTC, gamerson commented on gradle/apps/rest/src/main/java/com/liferay/blade/samples/rest/UsersRestService.java
> +	public void showLog() {
No one calls show log.  We should just add the logging in the component rest method or in the activate so they can see it activating.

2018-03-16 23:06 UTC, gamerson commented on gradle/extensions/doclib-resource-command-override/src/main/java/com/liferay/blade/samples/doclib/resourcecommand/override/CustomMVCResourceCommand.java
> +	public void showLog() {
No method calls this, so we need to add the log to another method that is called and possibly in the activate.

2018-03-16 23:06 UTC, gamerson commented on gradle/extensions/resource-bundle/src/main/java/com/liferay/blade/samples/resourcebundle/CustomResourceBundle.java
> +	public void showLog() {
move to activate

2018-03-20 17:49 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/857/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/857/consoleText)

2018-03-20 18:12 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761 against latest GA

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/270/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/270/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-ga/270/consoleText)

2018-03-20 18:34 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761 against latest 7.1

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/7/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/7/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7.1/7/consoleText)

2018-03-20 18:36 UTC, lrbladejenkinswindows commented
Bundles Diff Test Passed on LAX windows server on 30de624ea900d076c1da5fd50b85acb86ce3c761

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/531/)

2018-03-20 18:45 UTC, lrbladejenkins commented
Test failed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761 against latest 7010

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/131/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/131/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7010/131/consoleText)

2018-03-20 19:09 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761 against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/148/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/148/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-dxp/148/consoleText)

2018-03-20 19:21 UTC, lrbladejenkins commented
Test failed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761 against latest master

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/135/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/135/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-master/135/consoleText)

2018-03-20 21:47 UTC, lawrence-lee commented
@gamerson, I've fixed this with the changes you requested.

2018-03-23 15:41 UTC, lawrence-lee commented
ci:retest using this pull to test DXP SP7

2018-03-23 15:44 UTC, lrbladejenkins commented
Bundles Diff Test failed on LAX linux server on 30de624ea900d076c1da5fd50b85acb86ce3c761

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/858/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/858/consoleText)

2018-03-23 16:14 UTC, lrbladejenkins commented
Bundles Diff Test Passed on LAX linux server on 4aa89844c1956bb62938bb0278cc15a4b118ac79

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester/859/)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester/859/consoleText)

2018-03-23 16:37 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 4aa89844c1956bb62938bb0278cc15a4b118ac79 against latest GA

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/271/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-ga/271/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-ga/271/consoleText)

2018-03-23 16:47 UTC, lrbladejenkinswindows commented
Bundles Diff Test Passed on LAX windows server on 30de624ea900d076c1da5fd50b85acb86ce3c761

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/532/)

2018-03-23 17:00 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 4aa89844c1956bb62938bb0278cc15a4b118ac79 against latest 7.1

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/8/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7.1/8/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7.1/8/consoleText)

2018-03-23 17:13 UTC, lrbladejenkins commented
Test failed on LAX linux server on 4aa89844c1956bb62938bb0278cc15a4b118ac79 against latest 7010

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/132/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-7010/132/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-7010/132/consoleText)

2018-03-23 17:41 UTC, lrbladejenkins commented
Test Passed on LAX linux server on 4aa89844c1956bb62938bb0278cc15a4b118ac79 against latest DXP

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/149/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-dxp/149/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-dxp/149/consoleText)

2018-03-23 17:52 UTC, lrbladejenkinswindows commented
Bundles Diff Test Passed on LAX windows server on 4aa89844c1956bb62938bb0278cc15a4b118ac79

[link to jenkins](http://cloud-10-50-0-254:80/job/liferay-blade-samples-pr-tester/533/)

2018-03-23 17:54 UTC, lrbladejenkins commented
Test failed on LAX linux server on 4aa89844c1956bb62938bb0278cc15a4b118ac79 against latest master

[link to jenkins](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/136/)

[Test Report](http://cloud-10-50-0-245:8081/job/liferay-blade-samples-pr-tester-latest-master/136/testReport/api/json?pretty=true)

[Console output](http://cloud-10-50-0-245:8081//job/liferay-blade-samples-pr-tester-latest-master/136/consoleText)

2018-03-23 18:35 UTC, lawrence-lee commented
@gamerson ready to go

2018-03-30 15:04 UTC, merged